### PR TITLE
JI:770695 P2022-1907 Add favicon to our site

### PR DESCRIPTION
**Pull request by krysia1**

### CODE REVIEW

**Review by Reden4005 — COMMENTED** [review]
LGTM

**Review by Adys23 — APPROVED** [review]
LGTM

**Comment by piotrrawski** [comment]
LGTM

**Review by pawelwojdas — APPROVED** [review]

**Review by kacperChlon — APPROVED** [review]

**Review by aniasgit — APPROVED** [review]
LGTM :)

**Pull request merged**
